name: "Automated Merging"

on:
  workflow_dispatch:
    inputs:
      stateId:
        description: "State Id"
      eventName:
        description: "Event Name"
      eventPayload:
        description: "Event Payload"
      settings:
        description: "Settings"
      authToken:
        description: "Auth Token"
      ref:
        description: "Ref"

concurrency:
  group: ${{ github.workflow }}

jobs:
  compute:
    name: "Automated Merging"
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - run: ${{ toJSON(inputs) }}
        shell: cat {0}

      - name: Execute directive
        run: npx tsx ./src/main.ts
        id: automated-merging

      - name: Commit and Push DB updates
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add database/sql.db
          if [ -n "$(git diff-index --cached --name-only HEAD)" ]; then
            git commit -m "chore: [skip ci] updated database" || echo "Lint-staged check failed"
            git pull -X ours
            git push origin main
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
