name: "Update Configuration"

on:
  workflow_dispatch:
  push:

jobs:
  validate:
    name: "Validate Schema"
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"

      - name: Install deps and run configuration update
        run: |
          yarn install --immutable --immutable-cache --check-cache
          yarn tsx src/update-configuration.ts

      - name: Commit and Push generated types
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./manifest.json
          if [ -n "$(git diff-index --cached --name-only HEAD)" ]; then
            git commit -m "chore: updated generated configuration" || echo "Lint-staged check failed"
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}