name: "Update Configuration"

on:
  workflow_dispatch:
  push:

jobs:
  validate:
    name: "Validate Schema"
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"

      - name: Install deps and run configuration update
        run: |
          yarn install --immutable --immutable-cache --check-cache
          yarn tsc --project --noCheck tsconfig.json

      - name: Update manifest configuration using GitHub Script
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            // Load the plugin settings schema from the types file
            const { pluginSettingsSchema } = require('./src/types');

            // Read and parse the manifest file
            const manifestPath = path.resolve(__dirname, './manifest.json');
            const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));

            // Stringify the plugin settings schema and add it to the manifest
            const configuration = JSON.stringify(pluginSettingsSchema);
            console.log('Updated configuration:', configuration);

            // Add or update the configuration key in the manifest
            manifest["configuration"] = JSON.parse(configuration);

            // Write the updated manifest back to the file
            fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));
            console.log('Manifest updated successfully');

      - name: Commit and Push generated types
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./manifest.json
          if [ -n "$(git diff-index --cached --name-only HEAD)" ]; then
            git commit -m "chore: updated generated configuration" || echo "Lint-staged check failed"
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
