name: "Validate Schema"

on:
  workflow_dispatch:
    inputs:
      settings:
        description: "Settings"

jobs:
  validate:
    name: "Validate Schema"
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"

      - name: Install deps and run validation
        run: |
          yarn install --immutable --immutable-cache --check-cache
          yarn tsx src/validate-schema.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
